// export const GET_CELLS = "GET_CELLS";

export const GET_CHARACTERS_REQUEST = "GET_CHARACTERS_REQUEST";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_FAILURE = "GET_CHARACTERS_FAILURE";

export const CHARACTERS_MOVE_REQUEST = "CHARACTERS_MOVE_REQUEST";
export const CHARACTERS_MOVE_SUCCESS = "CHARACTERS_MOVE_SUCCESS";
export const CHARACTERS_MOVE_FAILURE = "CHARACTERS_MOVE_REQUEST";
// Auth actions
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const ERROR_CLEAN = "ERROR_CLEAN";
// Register actions
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const ERROR = "ERROR";
