# Generated by Django 3.0.2 on 2020-01-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell_type', models.CharField(max_length=20)),
                ('opacity', models.FloatField(default=0)),
                ('cell_id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_location_x', models.IntegerField(default=0)),
                ('cell_location_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('character_location_x', models.IntegerField(default=0)),
                ('character_location_y', models.IntegerField(default=0)),
            ],
        ),
    ]
