# Generated by Django 3.0.2 on 2020-01-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='cell_location_x',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cell_location_y',
        ),
    ]
