# Generated by Django 3.0.2 on 2020-01-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200108_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='cell_location_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cell',
            name='cell_location_y',
            field=models.IntegerField(default=0),
        ),
    ]
