# Generated by Django 3.0.2 on 2020-01-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200109_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_location_x',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_location_y',
            field=models.IntegerField(default=3),
        ),
    ]
